### ISSUE TITLE
Plugin nullifies effect of vscripts/modified triggers in stripper

### ISSUE THREAD

**Issue by sneak-it** [t5mat/crouchboostfix#3]
Absolutely butchered the title, but here we go:

I noticed after adding the latest major update of the plugin I am having issues with players being able to do things they shouldn't be.

For example, I specifically have a map modified with stripper to prevent telehopping, now players can.

Example value with stripper:
```
modify:
{
	match:
	{
	"classname" "trigger_teleport"
	"target" "spawn_02"
	}
	insert:
	{
	"OnStartTouch" "!activatorRunScriptCodeself.SetVelocity(Vector(0,0,0));0-1"
	}
}
```
With the plugin loaded, I can reliably bypass this vscript that was added, and immediately after unloading, the desired behavior returns. Almost 100% reproducible, with the plugin unloaded the issue does not occur.

**Comment by t5mat** [comment]
Hey, I cannot reproduce this, and neither can a friend that runs a SurfTimer server with Stripper and everything. This seems weird since the plugin doesn't deal with `trigger_teleport`s. Any more info/testing that you can do would be appreciated :)

**Comment by sneak-it** [comment]
Will do, sorry I have not had time to get to this yet.

**Comment by sneak-it** [comment]
A mere 363 days later (sorry), seems like this was resolved by either updating SM to latest stable, or Stripper to latest snapshot.
