### ISSUE TITLE
Latest release not being loaded

### ISSUE THREAD

**Issue by ghost** [t5mat/crouchboostfix#4]
crouchboostfix.smx: Unable to load plugin (unsupported feature set; code is too new)

This was the error on all my servers. Was doing sm plugins list to check a different plugin and noticed this (just updated yesterday). I reverted back to 2.0.1 as that one loads for me

**Comment by 1zc** [comment]
Seems like the compiled `.smx` in the release results in that error, maybe it was compiled with SM 1.11? Compiling it myself with SM 1.10 works fine.
